### ISSUE TITLE
abstract class in store.php

### ISSUE THREAD

**Issue by elieobeid7** [lavender/lavender#12]
I have this error

  Error Output: PHP Fatal error:  Class App\Database\Store contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (Lavender\Contracts\Entity\Model::setUnguardState) in /var/www/lavender/app/Database/Store.php on line 7     

Seems easy to fix, but just wanted to let you know

**Comment by ryaan-anthony** [comment]
I guess [removing methods](https://github.com/laravel/framework/commit/44084f213ff38ea417fd6b08cb30a0f1ee4fbceb) that [existed since L4](https://github.com/laravel/framework/blob/4.2/src/Illuminate/Database/Eloquent/Model.php#L2128) is not a breaking change. 

I suppose we'll have to be ready for a lot of that as L5 evolves. nbd

**Comment by ryaan-anthony** [comment]
fixed in latest tagged release 0.6.0
